name: auto-release

on:
  push:
    branches: ["release"]
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-window:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build (Window)
        run: cargo build --release --verbose

      - name: Archive
        shell: bash
        run: |
          mkdir archive
          cp env-template.env archive/
          cd archive
          mv env-template.env .env
          cp "../target/release/serenity-discord-bot.exe" ./
          7z a "serenity-discord-bot_windowns.7z" serenity-discord-bot.exe .env

      - name: Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            serenity-discord-bot_windowns.7z

  build-linux:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build (Linux)
        run: cargo build --release --verbose

      - name: Archive
        shell: bash
        run: |
          mkdir archive
          cp env-template.env archive/
          cd archive
          mv env-template.env .env
          cp "../target/release/serenity-discord-bot" ./
          7z a "serenity-discord-bot_linux.7z" serenity-discord-bot .env

      - name: Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            serenity-discord-bot_linux.7z
