name: build-release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose

    - name: Archive
      shell: bash
      run: |
        mkdir archive
        cd archive
        cp "../target/release/serenity-discord-bot.exe" ./
        7z a "serenity-discord-bot.7z" serenity-discord-bot.exe

    - name: Upload archive
      uses: actions/upload-artifact@v2
      with:
        name: serenity-discord-bot
        path: archive/serenity-discord-bot.7z

    - name: Discord Notify
      uses: th0th/notify-discord@v0.4.1
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_JOB_NAME: "Build Complete!"
        GITHUB_JOB_STATUS: ${{ job.status }}
      
