name: build-release-linux

on:
  workflow_dispatch:
    {}
  # push:
  #   branches: [ "master" ]
  #   paths: '**.rs'
  # pull_request:
  #   branches: [ "master" ]
  #   paths: '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose

    - name: Archive
      shell: bash
      run: |
        mkdir archive
        cd archive
        cp "../target/release/serenity-discord-bot" ./

    - name: Upload archive
      uses: actions/upload-artifact@v2
      with:
        name: serenity-discord-bot
        path: archive/serenity-discord-bot

    # - name: Discord Notify
    #   uses: tsickert/discord-webhook@v5.3.0
    #   with:
    #     webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
    #     content: "### New build action completed!"
    #     embed-title: ${{ github.workflow }} job#${{ github.run_id }}
    #     embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    #     embed-description: ${{ github.event.head_commit.message }}
    #     embed-color: 16539139
    #     embed-author-name: ${{ github.repository }}
    #     embed-author-url: ${{ github.server_url }}/${{ github.repository }}
    #     embed-author-icon-url: "https://raw.githubusercontent.com/JacKooDesu/serenity-discord-bot/master/arts/bot-icon.png"
    #     filename: archive/serenity-discord-bot.7z
      
