name: discord-webhook-tester

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Discord Notify
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "## New build action completed!"
        embed-title: "Action detail"
        embed-description: job#${{ github.run_id }}
        embed-color: "252, 94, 3"
        embed-author-icon-url: "https://raw.githubusercontent.com/JacKooDesu/serenity-discord-bot/master/arts/bot-icon.png"
        embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
