name: discord-webhook-tester

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Discord Notify
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "### New build action completed!"
        embed-title: ${{ github.event.head_commit }}
        embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        embed-description: job#${{ github.run_id }} | ${{ github.event.head_commit.message }}
        embed-color: 16539139
        embed-timestamp: ${{ steps.date.outputs.date }}
        embed-author-name: ${{ github.repository }}
        embed-author-url: ${{ github.server_url }}/${{ github.repository }}
        embed-author-icon-url: "https://raw.githubusercontent.com/JacKooDesu/serenity-discord-bot/master/arts/bot-icon.png"
